= Connection

To connect to TypeDB, you can use any TypeDB client.
See below guides on how to connect with different clients and drivers.

[cols-1]
--
.xref:guides::connection/studio.adoc[TypeDB Studio connection guide]
[.clickable]
****
A step-by-step guide on how to run and connect TypeDB Studio to TypeDB Cloud or Core.
****
//Integrated developer environment (IDE) with database manager, type browser, type editor, text editor, and file browser.

.xref:connection/console.adoc[TypeDB Console connection guide]
[.clickable]
****
A step-by-step guide on how to run and connect TypeDB Console to TypeDB Cloud or Core.
****

.xref:guides::connection/drivers-cloud.adoc[TypeDB driver to TypeDB Cloud connection guide]
[.clickable]
****
A step-by-step guide on how to use TypeDB drivers to connect to TypeDB Cloud.
****

.xref:guides::connection/drivers-core.adoc[TypeDB driver to TypeDB Core connection guide]
[.clickable]
****
A step-by-step guide on how to use TypeDB drivers to connect to TypeDB Core.
****
--
