= Account
:keywords: typedb, cloud, account, password, profile, settings
:longTailKeywords: typedb cloud account, account settings, password change
:pageTitle: Account
:summary: Personal account management.
:experimental:

== Account registration

// tag::create-account[]
During the alpha-testing period access to the TypeDB Cloud is restricted by invite-only policy.

To send a request to join alpha-test of TypeDB Cloud, use the following
https://typedb.com/deploy?dialog=cloud-waitlist[form].
// end::create-account[]

== Log In

// tag::log-in[]
Head to the https://cloud.typedb.com/[main page] of TypeDB CLoud and use credential, provided by Vaticle to log in.
// end::log-in[]

[#_log_out]
== Log out

On any page of the TypeDB Cloud web-portal click on the gear (⚙) icon in the top right corner and click on the *Log out*
option in the drop-down menu.

[#_settings]
== Account settings

To open setting for current account on any page of the TypeDB Cloud web-portal click on the gear (⚙) icon in
the top right corner and click on the *Settings* option.

=== Edit user details

Open an xref:cloud::account.adoc#_settings[Account settings]. In the User Details section click on the btn:[Edit]
button. Apply changes and click on the btn:[Submit] button.

=== Change password

To change the password of an account make sure to <<_log_out,log out>> of the TypeDB to get to the Log in page. Use the
*Forget password* link there and follow the instructions on screen.

== Join an organization, team, or project

=== Organization

include::cloud::user-management/organization.adoc[tag=intro]

include::cloud::user-management/organization.adoc[tag=join_organization]

=== Team




=== Project




