= Schema
[#_schema]

A TypeDB database schema defines a data model, like a blueprint.
It contains all user-defined xref:typeql::schema/types.adoc[types] and all
xref:typeql::schema/rules.adoc[rules] used in a database.

Every instance of data inserted to a TypeDB database must be assigned a type and be validated against constraints
defined in a schema.

[NOTE]
====
TypeDB removes the need to create a separate physical data model and allows developers to create schemas that mirror
their object model, simplifying design and development.
====

Any type in a TypeDB database has a single parent type or a supertype. Any type can be subtyped.

Any user-defined type is a subtype of either another user-defined type or a built-in type.

Any data in a TypeDB database is an instance of a user-defined type.

A TypeDB database schema is written in TypeQL and resemble a logical data models of relational databases.
TypeDB removes the need to create a separate physical data model and allows developers to create schemas that mirror
their object model, simplifying design and development.

As a result, TypeDB schemas look like entity-relationship (ER) diagrams with entities, relations, and attributes
connected by roles in relations, ownerships of attributes, and subtyping
(see xref:typeql::schema/types.adoc#_inheritance[inheritance]).
