= Schema
[#_schema]

A TypeDB database schema is like a blueprint of a database.
It defines types that can be stored in a database, including hierarchy of types,
ownership over attributes, possible roles in relations and other constraints, as well as rules, that can be used to
infer new data.

[IMPORTANT]
====
A database schema consists of user-defined xref:typeql::schema/types.adoc[types] and
xref:typeql::schema/rules.adoc[rules] used in a database.
====

Any user-defined type is a subtype of either another user-defined type or a built-in type.

Any data in a TypeDB database is an instance of a user-defined type.

A TypeDB database schema is written in TypeQL and resemble a logical data models of relational databases.
TypeDB removes the need to create a separate physical data model and allows developers to create schemas that mirror
their object model, simplifying design and development.

As a result, TypeDB schemas look like entity-relationship (ER) diagrams with entities, relations, and attributes
connected by roles in relations, ownerships of attributes, and subtyping
(see xref:typeql::schema/types.adoc#_inheritance[inheritance]).
