= Introduction

TypeQL is the query language of [TypeDB](https://github.com/vaticle/typedb). It is also:

- *Conceptual and intuitive*. TypeQL’s design is based directly on the [polymorphic conceptual data model]([https://typedb.com/philosophy](https://development.typedb.com/philosophy)) of TypeDB databases, providing syntax for working with entities, relation, and attributes, as well as inheritance and interfaces. TypeQL  is designed to closely mirrors natural language: its syntax is comprised of sequences of statements which often read just like sentences.
- *A fully variablizable language*. Any part of a TypeQL statement can be variablized, which can be used to express [parametric polymorphic](https://typedb.com/features#polymorphic-queries) statements. This enables TypeQL to express powerful parametric database operations.
- *Declarative and built for consistency.* TypeQL’s declarative statement-based syntax can be naturally interleaved with many other declarative constructs, including variable arithmetic or regular expressions. These additional constructs are integrated into TypeDB’s type system, which ensures consistency of any query sent to the database.

For a quick overview of the range of statements that are available in TypeQL check out our [TypeQL in 20 queries guide](…).



