= Sending a schema query
:experimental:

This guide covers sending a query in a schema session and write transaction with TypeDB Studio, Console, or drivers.
Make sure the selected client is xref:guides::installing/overview.adoc[installed].

== Query execution workflow

To send a schema query, we need to open a `schema` session to an existing database, and then open a `write` transaction.
After successful execution of the query, the transaction must be committed to persist the changes made to the schema.
See the full process outline below.

. Establish network connection to TypeDB. See the xref:guides::connection/overview.adoc[] section.
. Open a `schema` session.
. Open a `write` transaction.
. Send a query for execution.
. Commit changes.
. Close the session.

For more information on how to create a new database, see the xref:guides::database/overview.adoc[] section.

== How to send a schema query

The following instructions are written with the assumption that a connection to TypeDB is already established.
For a connection guide, see the xref:guides::connection/overview.adoc[] section.

//#todo Consider removing TypeQL query and query method from examples


== Learn more

If you don't have your own schema ready yet, feel free to use the
https://github.com/vaticle/typedb-docs/blob/master/typedb-src/modules/ROOT/attachments/iam-schema.tql[IAM schema,window=_blank].
For more information about the IAM schema, see the xref:typedb::tutorials/iam-schema.adoc[] page.